# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: gitsubmodule
    schedule:
      interval: 'daily'
      time: '03:00'
      timezone: 'America/New_York'
    directory: /

  # TODO: Go through and chunk updates into different groups by day so we do not block everything behind one big update

  - package-ecosystem: npm
    rebase-strategy: 'auto'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: '*'
        versions: ['version-update:semver-major']
      - dependency-name: 'eslint-plugin-unicorn' # Temporarily ignore this plugin until eslint support for flat file config
        versions: ['*']
      - dependency-name: 'typescript' # This is likely to conflight with peer dependencies and stop the whole dependency update process
        versions: ['*']

    groups:
      dependencies:
        patterns:
          - '*'
