# https://github.com/brianespinosa/.github

_extends: .github

repository:
  # The name of the repository. Changing this will rename the repository
  name: tacomawedge

  # A short description of the repository that will show up on GitHub
  description: Web site for Tacoma Wedge Historic District

  # A URL with more information about the repository
  homepage: https://tacomawedge.org

  # A comma-separated list of topics to set on the repository
  topics: react, nextjs, typescript

  # Either `true` to make the repository private, or `false` to make it public.
  private: false
