_extends: brianespinosa/settings:nextjs.yml

repository:
  name: tacomawedge
  description: Web site for Tacoma Wedge Historic District
  homepage: https://tacomawedge.org
  topics: react, nextjs, typescript
  private: false
