compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

logFilters:
  - code: YN0002
    level: error
  - code: YN0060
    level: error
  - code: YN0068
    level: error

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.7.0.cjs
