compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

logFilters:
  - code: YN0002
    level: error
  - code: YN0060
    level: error
  - code: YN0068
    level: error

nodeLinker: node-modules

packageExtensions:
  "@mdx-js/mdx@*":
    dependencies:
      acorn: ">=8.0.0 <9.0.0"
  eslint-plugin-jest@*:
    peerDependenciesMeta:
      typescript:
        optional: true

yarnPath: .yarn/releases/yarn-4.12.0.cjs
