name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: brianespinosa/checkout-setup-node-install@main
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: brianespinosa/checkout-setup-node-install@main
      - run: yarn test

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: brianespinosa/checkout-setup-node-install@main
      - run: yarn build
