name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          use-github-auto-merge: true
          target: 'minor'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: brianespinosa/checkout-setup-node-install@main
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: brianespinosa/checkout-setup-node-install@main
      - run: yarn test

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: brianespinosa/checkout-setup-node-install@main
      - uses: brianespinosa/next-build-cache@main
      - run: yarn build
